theme: jekyll-theme-minimal
source: /docs/
includes_dir: /
layouts_dir: /docs/_layouts/
plugins:
  - jekyll-feed
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: false
exclude:
 - hide/
