name: "Develop CI Build-Format-Lint-Test"

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
  repository_dispatch:

jobs:
  buildFormatLint:
    runs-on: ubuntu-latest
    steps:
      - name: build development image
        run: make build
      - name: run linter
        run: make lint
      - name: run formatter
        run: make format BLACK_ARGS=--check
  imageTest:
    needs: buildFormatLint
    runs-on: ubuntu-latest
    steps:
      - name: launch test env
        run: |
          make up_db
      - name: run tests
        run: make test
      - name: cleanup
        run: docker-compose down -v