name: "Develop CI Build-Format-Lint-Test"

on:
  push:
    branches:
      - develop
      - main
    paths:
      - '!Pipfile**'
      - '!Dockerfile'
      - '!Makefile'
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '!Pipfile**'
      - '!Dockerfile'
      - '!Makefile'
  workflow_dispatch:
  repository_dispatch:

jobs:
  buildFormatLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build development image
        run: make build
      - name: run linter
        run: make lint
