name: "Develop CI Build-Format-Lint-Test"

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  buildFormatLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-build-check
